// All states available in the data.gov.in Mandi API
export const MANDI_STATES = [
  "Andhra Pradesh",
  "Assam",
  "Chandigarh",
  "Chattisgarh",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

// All crops aligned with master products (display names)
export const MANDI_CROPS = [
  // Vegetables
  "Amaranthus",
  "Beetroot",
  "Bitter Gourd",
  "Bottle Gourd",
  "Brinjal",
  "Cabbage",
  "Capsicum",
  "Carrot",
  "Cauliflower",
  "Cluster Beans",
  "Coriander Leaves",
  "Cucumber",
  "Drumstick",
  "Garlic",
  "Ginger",
  "Green Chilli",
  "Green Peas",
  "Ladies Finger",
  "Methi Leaves",
  "Mint",
  "Mushroom",
  "Onion",
  "Pointed Gourd",
  "Potato",
  "Pumpkin",
  "Radish",
  "Ridge Gourd",
  "Snake Gourd",
  "Spinach",
  "Sponge Gourd",
  "Sweet Potato",
  "Tinda",
  "Tomato",
  "Turnip",
  // Fruits
  "Amla",
  "Apple",
  "Banana",
  "Custard Apple",
  "Grapes",
  "Guava",
  "Lemon",
  "Mango",
  "Muskmelon",
  "Orange",
  "Papaya",
  "Pineapple",
  "Pomegranate",
  "Sapota",
  "Watermelon",
];
